import { hexToRgb, rgbToHex, type RGB } from "./color";
import { sanitizeFontFamily } from "./font";
import { type BrandKit, type BrandTone } from "./designSystem";

export type ImportedBrandKit = {
  brandName: string; tagline: string; tone: BrandTone;
  primaryColor: RGB; secondaryColor: RGB; accentColor: RGB; backgroundColor: RGB; textColor: RGB;
  headlineFont: string; bodyFont: string; monoFont: string;
};

const BRAND_TONES: BrandTone[] = ["modern", "classic", "playful", "minimal", "bold"];
const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === "object" && value !== null;
const safeText = (value: unknown, fallback = "") => typeof value === "string" ? value.trim().slice(0, 200) || fallback : fallback;

function readColor(colors: Record<string, unknown>, name: string): RGB {
  const value = colors[name];
  if (typeof value !== "string") throw new Error(`Warna ${name} tidak ditemukan.`);
  const color = hexToRgb(value);
  if (!color) throw new Error(`Warna ${name} harus berupa kode HEX yang valid.`);
  return color;
}

export function parseBrandKitImport(text: string): ImportedBrandKit {
  let value: unknown;
  try { value = JSON.parse(text); } catch { throw new Error("File bukan JSON yang valid."); }
  if (!isRecord(value) || !isRecord(value.colors) || !isRecord(value.typography)) throw new Error("Struktur JSON Brand Kit tidak valid.");
  if (typeof value.tone !== "string" || !BRAND_TONES.includes(value.tone as BrandTone)) throw new Error("Tone Brand Kit tidak valid.");
  return {
    brandName: safeText(value.brandName, "My Brand"), tagline: safeText(value.tagline), tone: value.tone as BrandTone,
    primaryColor: readColor(value.colors, "primary"), secondaryColor: readColor(value.colors, "secondary"), accentColor: readColor(value.colors, "accent"),
    backgroundColor: readColor(value.colors, "background"), textColor: readColor(value.colors, "text"),
    headlineFont: sanitizeFontFamily(safeText(value.typography.headline, "Inter")), bodyFont: sanitizeFontFamily(safeText(value.typography.body, "Inter")), monoFont: sanitizeFontFamily(safeText(value.typography.mono, "JetBrains Mono")),
  };
}

export function brandKitToW3cTokens(kit: BrandKit): string {
  const color = (value: RGB) => ({ $type: "color", $value: rgbToHex(value) });
  return JSON.stringify({
    $description: `${kit.brandName} design tokens generated by CIKP Studio`,
    color: { primary: color(kit.primaryColor), secondary: color(kit.secondaryColor), accent: color(kit.accentColor), background: color(kit.backgroundColor), text: color(kit.textColor) },
    font: {
      headline: { $type: "fontFamily", $value: [kit.headlineFont, "sans-serif"] },
      body: { $type: "fontFamily", $value: [kit.bodyFont, "sans-serif"] },
      mono: { $type: "fontFamily", $value: [kit.monoFont, "monospace"] },
    },
  }, null, 2);
}

export function brandKitToTailwindConfig(kit: BrandKit): string {
  return `/** @type {import('tailwindcss').Config} */
export default {
  theme: { extend: {
    colors: { brand: { primary: '${rgbToHex(kit.primaryColor)}', secondary: '${rgbToHex(kit.secondaryColor)}', accent: '${rgbToHex(kit.accentColor)}', background: '${rgbToHex(kit.backgroundColor)}', text: '${rgbToHex(kit.textColor)}' } },
    fontFamily: { headline: ['${kit.headlineFont}', 'sans-serif'], body: ['${kit.bodyFont}', 'sans-serif'], mono: ['${kit.monoFont}', 'monospace'] },
  } },
};`;
}
