import { rgbToHex, type RGB } from "../../color";
import { type DesignSystem, type ShadowLayer } from "../model/designSystem";

const tokenKey = (value: string) => value.toLowerCase().replace(/\s+/g, "-").replace(/\./g, "_");
const cssName = (system: DesignSystem, category: string, name: string) =>
  `--${system.name}-${category}-${tokenKey(name)}`;

const numberFromCss = (value: string) => Number.parseFloat(value) || 0;
const dimension = (value: number, unit: "px" | "rem" = "px") => ({ value, unit });
const colorValue = (rgb: RGB, alpha = 1) => ({
  colorSpace: "srgb",
  components: [rgb.r / 255, rgb.g / 255, rgb.b / 255].map((value) => Number(value.toFixed(6))),
  alpha,
});

const shadowValue = (layer: ShadowLayer) => ({
  color: colorValue(layer.color, layer.alpha),
  offsetX: dimension(layer.offsetX),
  offsetY: dimension(layer.offsetY),
  blur: dimension(layer.blur),
  spread: dimension(layer.spread),
  ...(layer.inset ? { inset: true } : {}),
});

export function toCssVariables(system: DesignSystem): string {
  const lines: string[] = [
    `/* ${system.name} · ${system.mode} */`,
    ":root {",
    "  /* Semantic colors */",
  ];
  system.colors.forEach((color) => {
    lines.push(`  ${cssName(system, "color", color.token)}: ${color.hex};`);
  });
  lines.push("", "  /* Primitive shade scale */");
  system.shades.forEach((shade) => {
    lines.push(`  ${cssName(system, "shade", String(shade.step))}: ${rgbToHex(shade.rgb)};`);
  });
  lines.push(
    "",
    "  /* Typography */",
    `  ${cssName(system, "font", "family")}: ${JSON.stringify(system.fontFamily)}, sans-serif;`,
  );
  system.typography.forEach((type) => {
    const prefix = cssName(system, "text", type.name);
    lines.push(`  ${prefix}-size: ${type.size};`);
    lines.push(`  ${prefix}-line-height: ${type.lineHeight};`);
    lines.push(`  ${prefix}-weight: ${type.fontWeight};`);
    lines.push(`  ${prefix}-tracking: ${type.letterSpacing};`);
  });
  lines.push("", "  /* Spacing */");
  system.spacing.forEach((space) => {
    lines.push(`  ${cssName(system, "space", space.name)}: ${space.value};`);
  });
  lines.push("", "  /* Border radius */");
  system.radius.forEach((radius) => {
    lines.push(`  ${cssName(system, "radius", radius.name)}: ${radius.value};`);
  });
  lines.push("", "  /* Shadows */");
  system.shadows.forEach((shadow) => {
    lines.push(`  ${cssName(system, "shadow", shadow.name)}: ${shadow.css};`);
  });
  lines.push("", "  /* Component aliases */");
  system.componentColors.forEach((token) => {
    lines.push(
      `  --${system.name}-${token.component}-${token.property}: var(${cssName(system, "color", token.reference)});`,
    );
  });
  lines.push("}");
  return lines.join("\n");
}

export function toTailwindConfig(system: DesignSystem): string {
  const lines = [
    `/* Tailwind CSS v4 theme · ${system.name} · ${system.mode} */`,
    '@import "tailwindcss";',
    "",
    "@theme {",
    `  --font-${system.name}: ${JSON.stringify(system.fontFamily)}, sans-serif;`,
  ];
  system.colors.forEach((color) => {
    lines.push(`  --color-${system.name}-${color.token}: ${color.hex};`);
  });
  system.shades.forEach((shade) => {
    lines.push(`  --color-${system.name}-${shade.step}: ${rgbToHex(shade.rgb)};`);
  });
  system.spacing.forEach((space) => {
    lines.push(`  --spacing-${system.name}-${tokenKey(space.name)}: ${space.value};`);
  });
  system.radius.forEach((radius) => {
    lines.push(`  --radius-${system.name}-${radius.name}: ${radius.value};`);
  });
  system.shadows.forEach((shadow) => {
    lines.push(`  --shadow-${system.name}-${shadow.name}: ${shadow.css};`);
  });
  system.typography.forEach((type) => {
    const key = tokenKey(type.name);
    lines.push(`  --text-${system.name}-${key}: ${type.size};`);
    lines.push(`  --leading-${system.name}-${key}: ${type.lineHeight};`);
    lines.push(`  --font-weight-${system.name}-${key}: ${type.fontWeight};`);
    lines.push(`  --tracking-${system.name}-${key}: ${type.letterSpacing};`);
  });
  lines.push("}");
  return lines.join("\n");
}

export function toJsonTokens(system: DesignSystem): string {
  const typography = Object.fromEntries(
    system.typography.map((type) => {
      const fontSizeRem = numberFromCss(type.size);
      const trackingRem = Number((fontSizeRem * numberFromCss(type.letterSpacing)).toFixed(4));
      return [
        tokenKey(type.name),
        {
          $type: "typography",
          $value: {
            fontFamily: type.fontFamily,
            fontSize: dimension(fontSizeRem, "rem"),
            fontWeight: type.fontWeight,
            letterSpacing: dimension(trackingRem, "rem"),
            lineHeight: type.lineHeight,
          },
          $description: type.usage,
        },
      ];
    }),
  );

  const tokens = {
    $schema: "https://www.designtokens.org/schemas/2025.10/format.json",
    [system.name]: {
      $description: `${system.name} ${system.mode} design tokens generated by ALUSNA`,
      primitive: {
        color: {
          $type: "color",
          ...Object.fromEntries(
            system.shades.map((shade) => [
              String(shade.step),
              { $value: colorValue(shade.rgb), $description: `Brand shade ${shade.step}` },
            ]),
          ),
        },
      },
      semantic: {
        color: {
          $type: "color",
          ...Object.fromEntries(
            system.colors.map((color) => [
              color.token,
              { $value: colorValue(color.rgb), $description: color.usage },
            ]),
          ),
        },
      },
      component: {
        color: Object.fromEntries(
          [...new Set(system.componentColors.map((token) => token.component))].map((component) => [
            component,
            Object.fromEntries(
              system.componentColors
                .filter((token) => token.component === component)
                .map((token) => [
                  token.property,
                  {
                    $type: "color",
                    $value: `{${system.name}.semantic.color.${token.reference}}`,
                    $description: token.usage,
                  },
                ]),
            ),
          ]),
        ),
      },
      typography,
      spacing: {
        $type: "dimension",
        ...Object.fromEntries(
          system.spacing.map((space) => [
            tokenKey(space.name),
            { $value: dimension(space.px), $description: space.usage },
          ]),
        ),
      },
      radius: {
        $type: "dimension",
        ...Object.fromEntries(
          system.radius.map((radius) => [
            radius.name,
            { $value: dimension(radius.px), $description: radius.usage },
          ]),
        ),
      },
      shadow: {
        $type: "shadow",
        ...Object.fromEntries(
          system.shadows.map((shadow) => [
            shadow.name,
            {
              $value:
                shadow.layers.length === 1
                  ? shadowValue(shadow.layers[0])
                  : shadow.layers.map(shadowValue),
              $description: shadow.usage,
            },
          ]),
        ),
      },
    },
  };
  return JSON.stringify(tokens, null, 2);
}

export function toReactNativeTheme(system: DesignSystem): string {
  const theme = {
    mode: system.mode,
    colors: Object.fromEntries(system.colors.map((color) => [color.token, color.hex])),
    typography: Object.fromEntries(
      system.typography.map((type) => [
        tokenKey(type.name),
        {
          fontFamily: type.fontFamily,
          fontSize: numberFromCss(type.size) * 16,
          lineHeight: numberFromCss(type.size) * 16 * type.lineHeight,
          fontWeight: String(type.fontWeight),
          letterSpacing: Number(
            (numberFromCss(type.size) * 16 * numberFromCss(type.letterSpacing)).toFixed(4),
          ),
        },
      ]),
    ),
    spacing: Object.fromEntries(system.spacing.map((space) => [tokenKey(space.name), space.px])),
    borderRadius: Object.fromEntries(system.radius.map((radius) => [radius.name, radius.px])),
  };
  return `// theme.ts\nexport const theme = ${JSON.stringify(theme, null, 2)} as const;\n\nexport type AppTheme = typeof theme;`;
}

export function toScssVariables(system: DesignSystem): string {
  return toCssVariables(system)
    .replace(/^\/\*[\s\S]*?\*\/\n:root \{/, `// ${system.name} · ${system.mode}`)
    .replace(new RegExp(`var\\(--${system.name}-([a-z0-9_-]+)\\)`, "g"), `$${system.name}-$1`)
    .replace(/^  --/gm, "$")
    .replace(/;\n?}$/, ";");
}

export type ExportFormat = "css" | "tailwind" | "json" | "react-native" | "scss";

export const EXPORT_FILE_META: Record<ExportFormat, { extension: string; mime: string }> = {
  css: { extension: "css", mime: "text/css" },
  tailwind: { extension: "css", mime: "text/css" },
  json: { extension: "tokens.json", mime: "application/json" },
  "react-native": { extension: "theme.ts", mime: "text/typescript" },
  scss: { extension: "scss", mime: "text/x-scss" },
};

export function exportDesignSystem(system: DesignSystem, format: ExportFormat): string {
  switch (format) {
    case "css":
      return toCssVariables(system);
    case "tailwind":
      return toTailwindConfig(system);
    case "json":
      return toJsonTokens(system);
    case "react-native":
      return toReactNativeTheme(system);
    case "scss":
      return toScssVariables(system);
  }
}
