import { useMemo } from "react";
import { rgbToHex } from "../../lib/color";
import { Card, CardHeader, CardBody } from "../../components/Card";
import { useToast } from "../../components/toastContext";
import { type BrandKit } from "../../lib/designSystem";

// ---------------------------------------------------------------------------
// Export Tab
// ---------------------------------------------------------------------------

export function ExportTab({
  kit,
  onExportHtml,
  onExportJson,
  onExportW3cTokens,
  onExportTailwind,
}: {
  kit: BrandKit;
  onExportHtml: () => void;
  onExportJson: () => void;
  onExportW3cTokens: () => void;
  onExportTailwind: () => void;
}) {
  const { show } = useToast();

  const jsonPreview = useMemo(() => {
    return JSON.stringify(
      {
        brandName: kit.brandName,
        tagline: kit.tagline,
        tone: kit.tone,
        colors: {
          primary: rgbToHex(kit.primaryColor),
          secondary: rgbToHex(kit.secondaryColor),
          accent: rgbToHex(kit.accentColor),
          background: rgbToHex(kit.backgroundColor),
          text: rgbToHex(kit.textColor),
        },
        typography: {
          headline: kit.headlineFont,
          body: kit.bodyFont,
          mono: kit.monoFont,
        },
      },
      null,
      2,
    );
  }, [kit]);

  const scssPreview = useMemo(() => {
    return `// Brand Kit SCSS Variables
// Generated by ColorKit

// Colors
$brand-primary: ${rgbToHex(kit.primaryColor)};
$brand-secondary: ${rgbToHex(kit.secondaryColor)};
$brand-accent: ${rgbToHex(kit.accentColor)};
$brand-background: ${rgbToHex(kit.backgroundColor)};
$brand-text: ${rgbToHex(kit.textColor)};

// Typography
$brand-headline-font: '${kit.headlineFont}', sans-serif;
$brand-body-font: '${kit.bodyFont}', sans-serif;
$brand-mono-font: '${kit.monoFont}', monospace;

// Brand Info
$brand-name: '${kit.brandName}';
$brand-tagline: '${kit.tagline}';
$brand-tone: '${kit.tone}';`;
  }, [kit]);

  const reactNativePreview = useMemo(() => {
    return `// Brand Kit React Native Theme
// Generated by ColorKit

export const brandTheme = {
  colors: {
    primary: '${rgbToHex(kit.primaryColor)}',
    secondary: '${rgbToHex(kit.secondaryColor)}',
    accent: '${rgbToHex(kit.accentColor)}',
    background: '${rgbToHex(kit.backgroundColor)}',
    text: '${rgbToHex(kit.textColor)}',
  },
  typography: {
    headlineFont: '${kit.headlineFont}',
    bodyFont: '${kit.bodyFont}',
    monoFont: '${kit.monoFont}',
  },
  brand: {
    name: '${kit.brandName}',
    tagline: '${kit.tagline}',
    tone: '${kit.tone}',
  },
} as const;

export type BrandTheme = typeof brandTheme;`;
  }, [kit]);

  return (
    <div className="space-y-4 animate-fade-in">
      {/* Export Options */}
      <Card>
        <CardHeader title="Export Options" subtitle="Download your brand kit" />
        <CardBody>
          <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">
            <button
              type="button"
              onClick={onExportHtml}
              className="flex items-center gap-3 rounded-xl border p-4 text-left transition hover:border-indigo-500/50"
              style={{ borderColor: "var(--border)", backgroundColor: "var(--chip-bg)" }}
            >
              <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-indigo-500/15 text-xl">
                📄
              </div>
              <div>
                <div className="text-sm font-semibold" style={{ color: "var(--text-primary)" }}>
                  HTML Guidelines
                </div>
                <div className="text-[11px]" style={{ color: "var(--text-muted)" }}>
                  Beautiful brand guidelines page
                </div>
              </div>
            </button>
            <button
              type="button"
              onClick={onExportJson}
              className="flex items-center gap-3 rounded-xl border p-4 text-left transition hover:border-indigo-500/50"
              style={{ borderColor: "var(--border)", backgroundColor: "var(--chip-bg)" }}
            >
              <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-emerald-500/15 text-xl">
                📦
              </div>
              <div>
                <div className="text-sm font-semibold" style={{ color: "var(--text-primary)" }}>
                  JSON Brand Kit
                </div>
                <div className="text-[11px]" style={{ color: "var(--text-muted)" }}>
                  Structured data for integrations
                </div>
              </div>
            </button>
            <button
              type="button"
              onClick={onExportW3cTokens}
              className="flex items-center gap-3 rounded-xl border p-4 text-left transition hover:border-indigo-500/50"
              style={{ borderColor: "var(--border)", backgroundColor: "var(--chip-bg)" }}
            >
              <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-sky-500/15 text-xs font-bold">
                W3C
              </div>
              <div>
                <div className="text-sm font-semibold" style={{ color: "var(--text-primary)" }}>
                  W3C Design Tokens
                </div>
                <div className="text-[11px]" style={{ color: "var(--text-muted)" }}>
                  JSON token standard
                </div>
              </div>
            </button>
            <button
              type="button"
              onClick={onExportTailwind}
              className="flex items-center gap-3 rounded-xl border p-4 text-left transition hover:border-indigo-500/50"
              style={{ borderColor: "var(--border)", backgroundColor: "var(--chip-bg)" }}
            >
              <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-cyan-500/15 text-xs font-bold">
                TW
              </div>
              <div>
                <div className="text-sm font-semibold" style={{ color: "var(--text-primary)" }}>
                  Tailwind Config
                </div>
                <div className="text-[11px]" style={{ color: "var(--text-muted)" }}>
                  Ready-to-use theme extension
                </div>
              </div>
            </button>
            <button
              type="button"
              onClick={() => {
                navigator.clipboard.writeText(jsonPreview);
                show("✓ Brand kit JSON copied!");
              }}
              className="flex items-center gap-3 rounded-xl border p-4 text-left transition hover:border-indigo-500/50"
              style={{ borderColor: "var(--border)", backgroundColor: "var(--chip-bg)" }}
            >
              <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-amber-500/15 text-xl">
                📋
              </div>
              <div>
                <div className="text-sm font-semibold" style={{ color: "var(--text-primary)" }}>
                  Copy JSON
                </div>
                <div className="text-[11px]" style={{ color: "var(--text-muted)" }}>
                  Copy to clipboard
                </div>
              </div>
            </button>
            <button
              type="button"
              onClick={() => {
                const cssVars = `:root {\n  --brand-primary: ${rgbToHex(kit.primaryColor)};\n  --brand-secondary: ${rgbToHex(kit.secondaryColor)};\n  --brand-accent: ${rgbToHex(kit.accentColor)};\n  --brand-bg: ${rgbToHex(kit.backgroundColor)};\n  --brand-text: ${rgbToHex(kit.textColor)};\n}`;
                navigator.clipboard.writeText(cssVars);
                show("✓ CSS Variables copied!");
              }}
              className="flex items-center gap-3 rounded-xl border p-4 text-left transition hover:border-indigo-500/50"
              style={{ borderColor: "var(--border)", backgroundColor: "var(--chip-bg)" }}
            >
              <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-rose-500/15 text-xl">
                🎨
              </div>
              <div>
                <div className="text-sm font-semibold" style={{ color: "var(--text-primary)" }}>
                  CSS Variables
                </div>
                <div className="text-[11px]" style={{ color: "var(--text-muted)" }}>
                  Copy CSS custom properties
                </div>
              </div>
            </button>
            <button
              type="button"
              onClick={() => {
                navigator.clipboard.writeText(scssPreview);
                show("✓ SCSS Variables copied!");
              }}
              className="flex items-center gap-3 rounded-xl border p-4 text-left transition hover:border-indigo-500/50"
              style={{ borderColor: "var(--border)", backgroundColor: "var(--chip-bg)" }}
            >
              <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-pink-500/15 text-xl">
                💅
              </div>
              <div>
                <div className="text-sm font-semibold" style={{ color: "var(--text-primary)" }}>
                  SCSS Variables
                </div>
                <div className="text-[11px]" style={{ color: "var(--text-muted)" }}>
                  Copy SCSS variables
                </div>
              </div>
            </button>
            <button
              type="button"
              onClick={() => {
                navigator.clipboard.writeText(reactNativePreview);
                show("✓ React Native theme copied!");
              }}
              className="flex items-center gap-3 rounded-xl border p-4 text-left transition hover:border-indigo-500/50"
              style={{ borderColor: "var(--border)", backgroundColor: "var(--chip-bg)" }}
            >
              <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-cyan-500/15 text-xl">
                📱
              </div>
              <div>
                <div className="text-sm font-semibold" style={{ color: "var(--text-primary)" }}>
                  React Native Theme
                </div>
                <div className="text-[11px]" style={{ color: "var(--text-muted)" }}>
                  Copy React Native theme
                </div>
              </div>
            </button>
          </div>
        </CardBody>
      </Card>

      {/* Preview Tabs */}
      <Card>
        <CardHeader title="Preview" subtitle="Brand kit data structure" />
        <CardBody>
          <div className="space-y-4">
            <div className="flex gap-2">
              <button
                type="button"
                onClick={() => {
                  navigator.clipboard.writeText(jsonPreview);
                  show("✓ JSON copied!");
                }}
                className="rounded-lg border px-3 py-1.5 text-xs transition"
                style={{ borderColor: "var(--border)", color: "var(--text-secondary)" }}
              >
                Copy JSON
              </button>
              <button
                type="button"
                onClick={() => {
                  navigator.clipboard.writeText(scssPreview);
                  show("✓ SCSS copied!");
                }}
                className="rounded-lg border px-3 py-1.5 text-xs transition"
                style={{ borderColor: "var(--border)", color: "var(--text-secondary)" }}
              >
                Copy SCSS
              </button>
              <button
                type="button"
                onClick={() => {
                  navigator.clipboard.writeText(reactNativePreview);
                  show("✓ React Native copied!");
                }}
                className="rounded-lg border px-3 py-1.5 text-xs transition"
                style={{ borderColor: "var(--border)", color: "var(--text-secondary)" }}
              >
                Copy React Native
              </button>
            </div>
            <div
              className="max-h-80 overflow-auto rounded-xl border p-4 text-[11px] leading-relaxed"
              style={{
                borderColor: "var(--border)",
                backgroundColor: "var(--surface)",
                color: "var(--text-secondary)",
              }}
            >
              <pre className="whitespace-pre-wrap">{jsonPreview}</pre>
            </div>
          </div>
        </CardBody>
      </Card>
    </div>
  );
}
